library(shiny)
library(glue)

#renders will alloq output
ui <- fluidPage(
  sidebarLayout(
    sidebarPanel(
      textInput("title", "Title"),
      numericInput("x_max", "Maximum x axis value", value = 10, min = 1),
      textInput("generated_by", "Generated by:")
    ),
    mainPanel(
      plotOutput("sine"), #...Output function used to do output  - ID should be unique as per inputs
      tableOutput("plot_table"),
      textOutput("gen_by")
    )
  )
)

server <- function(input, output, session) {
  output$sine <- renderPlot({ #if we want output, we put output$... where ... is unique ID
    plot_data <- data.frame( #
      x = seq(0, input$x_max, by = 0.1),
      y = sin(seq(0, input$x_max, by = 0.1))
    )
    plot(plot_data$x, plot_data$y, main = input$title, type = "l") #we can output standard plot R plot
    #plot is dynamic as the code is rendered everytime a value changess
  })
  
  output$plot_table <- renderTable({
    plot_data <- data.frame(
      x = seq(0, input$x_max, by = 0.1),
      y = sin(seq(0, input$x_max, by = 0.1))
    )
    plot_data
  })
  
  output$gen_by <- renderText({
    glue("Chart generated by {input$generated_by}")#glue function is used for text interpolation 
  #  paste0("text and name ",input$generated_by) #paste can also be used
  })
}

shinyApp(ui, server)

